- mix.exs
- mix.lock
Allows for using phoenix_html 2.3
Closes #3
> Relax version requirement for phoenix_html

- lib/scrivener/html.ex
The `params` list didn't get forwarded to `raw_pagination_links` and thus the `next`, `previous`, ... options didn't work.
Second commit fixes a warnig with newer Elixir versions
> Fixing a bug in _pagination_links

- lib/scrivener/html.ex
- mix.exs
- test/scrivener/html_test.exs
Small fix that correctly generates bootstrap pagination html
> FIX: Bootstrap active class is set on the li, not the a element

- README.md
- lib/scrivener/html.ex
- test/scrivener/html_test.exs
Hello,
I implemented the Foundation for Sites 6.x styling (though I think it'd work for Foundation 5.x as well). I updated an affected test and added another test for Foundation styling.
Since this now makes three visual styles, I could update the README to note the different styles it now supports.
Let me know if you need anything else.
Thanks
> Implemented Foundation for Sites 6.x style

- lib/scrivener/html.ex
- test/scrivener/html_test.exs
I have two separately paginated lists on the same page. The only thing that keeps me from doing that with `scrivener_html` is the fact that the `:page` param name is hard-coded.
This PR is an attempt at allowing the customization of the `:page` param name. It is used like so:
<%= pagination_links @conn, @page, page_param: :custom_page_name %>
> Allow custom page param name

- README.md
When call pagination_links function with additional parameter(e.g. locale), it raises error without :path option.
> fix pagination_links option explanation

- lib/scrivener/html.ex
- test/scrivener/html_test.exs
More coherent to always put the previous sign in the front, also when first page is enabled. This is in line with the behaviour of last and next.
> Fix previous positioning

- mix.exs
- mix.lock
- test/scrivener/html_test.exs
Also removed usage of the deprecated test helper `conn/0` in favor of `build_conn/0`.
> Relax version requirement to support Phoenix 1.2

- mix.exs
Phoenix 1.2 just launched. Proposing a small change to remove the `-rc` from the versioned phoenix in `mix.exs`.
> Update mix.exs for Phoenix 1.2

- lib/scrivener/html.ex
- test/scrivener/html_test.exs
The ellipsis placement logic was reversed (more or less), and it also tried to render `&hellip;` directly in a `content_tag`, causing it to be escaped into `&amp;hellip;`.
This pull request fixes both issues, at least as far as I can tell by the added / modified tests and the Phoenix app I'm using Scrivener.HTML in.
_**NOTE:** I enabled the "Foundation for Sites 6.x" ellipsis test (which was missing `==` after the expected output), and modified it to match the actual HTML that's output by `HTML.pagination_links`.. except for the incorrectly rendered ellipsis, of course._
> Fix ellipsis rendering (logic + formatting)

- mix.exs
After opening #27 I thought to myself, "maybe it already works with Scrivener 2 and we just need to relax the dependency?"
So I tried it out and all tests pass with `{:scrivener, "~> 2.0.0"}` in the deps (it also works well in my app, fwiw). This PR relaxes the constraint to let `scrivener_html` run with either version.
> optionally run with Scrivener 2

- mix.exs
- test/scrivener/html_test.exs
- test/test_helper.exs
Elixir 1.3 adds describe functionality to ExUnit, which conflicts w/ Pavlov and breaks the test suite. Here's the changes necessary to remove Pavlov and use 1.3's describe instead.
You probably won't need this until you're ready to go Elixir 1.3 only, but I made these changes when running the tests for #28 and I figured I'd at least create the PR to save you the effort when you get there.
> remove Pavlov in favor of Elixir 1.3’s `describe`

- mix.exs
This allows `scrivener_html` to work with the newer versions of `scrivener` (`2.1.x`).
> Loosen scrivener 2.0 version requirement

- LICENSE
Dear Matt,
Would you please consider adding a license to this library?
Both [scrivener](https://github.com/drewolson/scrivener/blob/master/LICENSE) and [scrivener_ecto](https://github.com/drewolson/scrivener_ecto/blob/master/LICENSE) are licensed under the MIT license.
Explicitly adding a license would makes it significantly easier to use your project as a dependency.
For your convenience I have structured this issue as a pull request with a sample license MIT attached. Feel free to merge if convenient. I took the license text as found in `scrivener` and `scrivener_ecto` and changed the name to be yours.
Thanks, 
Sebastian
> Would you please consider adding a license to this library?

- lib/scrivener/html.ex
- mix.exs
- test/scrivener/html_test.exs
I was trying to pass a nested keyword list as a query param to the pagination_links function:
```
pagination_links(@orders, [q: [name: "joe"]])
```
I was getting the following error:
```
** (exit) an exception was raised:
** (ArgumentError) cannot convert the given list to a string.
To be converted to a string, a list must contain only:
* strings
* integers representing Unicode codepoints
* or a list containing one of these three elements
Please check the given list or call inspect/1 to get the list representation, got:
[name: "joe"]
(elixir) lib/list.ex:624: List.to_string/1
(scrivener_html) lib/scrivener/html.ex:41: anonymous fn/2 in Scrivener.HTML.Default.path/3
```
I replaced the code that generates the query params by the `Plug.Conn.Query.encode` function. I think it will make the …
> adding support for params defined with a keyword list

- mix.exs
warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
scrivener_html/mix.exs:20
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
scrivener_html/mix.exs:21
warning: variable "aliases" does not exist and is being expanded to "aliases()", please use parentheses to remove the ambiguity or change the variable name
scrivener_html/mix.exs:22
> Fix warnings Elixir 1.4

- lib/scrivener/html.ex
- test/scrivener/html_test.exs
If you use first/last, then the "distance" required before showing
an ellipsis should be one greater than the current implementation.
Example of bug:
If you have 3 total pages, using first/last true (which is the default)
and you're on page 1, you're links would be 1, 2, ..3
> Fix bug for extra ellipsis when using first/last

- lib/scrivener/html.ex
Fixes #50 
@nlap I don't know what else to do except `++` these two lists together since one will most definately be a true keyword list and the other won't. The other option was to try to turn the second list into a true keyword list, but that would mean converting `page_param` into an atom when it is already an integer. This to me seems more dangerous because of the number of atoms it could create. Seems the lesser of two evils is to use `++`.
> Elixir 1.4 -- Keyword.merge/2 throws exception on improper keyword list

- README.md
- lib/scrivener/html.ex
- test/scrivener/html_test.exs
As the other branch has seem to go stale & the css/classes is out of date to the current version of Bulma, here is the updated version.
I've opted to use the default `is-centered` as described here ~ http://bulma.io/documentation/components/pagination/
As it allow's for the `ellipsis` to sit nicely within the list without the need for the outside the ul elements
This is an example from my current Phoenix app.
Let me know if there is anything else i need to add :-)
B
> add bulma 0.4.x support

- lib/scrivener/html.ex
- test/scrivener/html_test.exs
fixes #72
The first page of a paginated page should be referred to without
the page parameter to make sure Google sees the link as a link to the
first page and not have two links (/ and /page=1) link to the same page.
> Remove page=1 query parameter because of SEO reasons

- lib/scrivener/html.ex
Elixir 1.5+ shall be deprecating this operation.
I just added parentheses to fix this and also support earlier Elixir versions.
See the reported warning below:
"not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions.
> Updated usage of "not expr1 in expr2" to support Elixir 1.5+

- mix.exs
The `source_url` needs to be an url.
This fixes the "View Source" buttons url in on hexdocs.pm that previously was `git@github.com:mgwidmann/scrivener_html.git`
The `View Source` button:
It's url:
> fix: source_url in Mix file

- lib/scrivener/html.ex
- test/scrivener/html_test.exs
I need to hide pagination when total pages are one/zero. There is also related issue here, https://github.com/mgwidmann/scrivener_html/issues/75.
This PR adds a global option with key `hide_single` or you can set it as an option in `pagination_links` function i.e. `pagination_links(conn, page, hide_single: true)`. (also open to change the option to a different name, can't think of a better name at the moment).
All tests are passing. Let me know if this is something you like or don't like. I'm okay with either decision. I can definitely hide the pagination in the template, but it's probably convenient to have it as an option.
> Add option to hide pagination for single page result
